#!/usr/bin/env bash
#displays number from 1 to 100
count=1
while [ $count -lt 101 ]
do
       if [ $((count%15)) = 0 ]
       then
            echo "FizzBuzz"
       elif [ $((count%3)) = 0 ]
       then
             echo "Fizz"
       elif [$((count%5)) = 0 ]
       then
             echo "Buzz"
       else
             echo "$count"
       fi
       count =$(( count + 1 ))
done
