#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

count=0

while [ $count -lt 10 ]
do
 if [ count -eq ]
 then
   echo "bad luck"
 elif [ $count -eq 7 ]
 then
  echo "good luck"
 else
   echo "Best School"
 fi
 (( countt++ ))
done
