#!/usr/bin/env bash
#Display a list 0f current running processes.
#Must show all processes, for all users, including those which might not have a TTY
#Display in a user-oriented format
#Show process hierarchy

ps -axuf
